spring.application.name=store
server.port=8080

###################################
#           docker
###################################
spring.docker.compose.enabled=true
#spring.docker.compose.file=D:/COMP5348/Tutorial-07-Group-08/Store/store-app/compose.yaml
###################################
#           logger
###################################
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.yourapp=DEBUG
# colorful
spring.output.ansi.enabled=ALWAYS
# output
logging.file.name=logs/app.log

###################################
#               jwt
###################################
app.jwt.secret=change-this-very-long-random-secret-at-least-256-bits
app.jwt.issuer=demo-store
app.jwt.expires-days=7

###################################
#       openapi - swagger
###################################
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
openapi.dev-url=http://localhost:8080
openapi.prod-url=http://localhost:8080
springdoc.swagger-ui.path=/docs

###################################
#            database
###################################
spring.datasource.url=jdbc:postgresql://localhost:5433/store
spring.datasource.username=admin
spring.datasource.password=admin

# initialize item data on app startup
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:db/test/insert_items1.sql

###################################
#               jpa
###################################
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update
#spring.jpa.open-in-view=false

###################################
#           RabbitMQ
###################################
management.health.rabbit.enabled=false
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

# Prevent listening exceptions from causing infinite reentry into the queue
spring.rabbitmq.listener.simple.default-requeue-rejected=false

###################################
#              gRPC
###################################
grpc.client.warehouse1.address=localhost:9091
grpc.client.warehouse1.negotiation-type=plaintext
grpc.client.warehouse2.address=localhost:9092
grpc.client.warehouse2.negotiation-type=plaintext

