server.port=8082

###################################
#            grpc server
###################################
grpc.server.port=9092
warehouse.id=WH-02

###################################
#               jpa
###################################
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update


###################################
#            database
###################################
spring.datasource.url=jdbc:postgresql://localhost:5433/warehouse2
spring.datasource.username=admin
spring.datasource.password=admin

spring.application.name=warehouse2

# initialize stock data on warehouse2 startup
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:db/insert_stock2.sql



