spring.application.name=BankApp

server.port=8086

###################################
#       openapi - swagger
###################################
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
openapi.dev-url=http://localhost:8086
openapi.prod-url=http://localhost:8086
springdoc.swagger-ui.path=/docs

###################################
#            database
###################################
spring.datasource.url=jdbc:postgresql://localhost:5436/bank
spring.datasource.username=admin
spring.datasource.password=admin

###################################
#               jpa
###################################
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# 把 SQL/DDL 打印出来，便于确认是否在建表
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace

###################################
#           docker
###################################
# 临时关闭docker测试
spring.docker.compose.enabled=true

###################################
#           logger
###################################
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.yourapp=DEBUG
# colorful
spring.output.ansi.enabled=ALWAYS
# output
logging.file.name=logs/app.log