spring.application.name=EmailService

server.port=0

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

email.templates.defaultLocale=en_AU
messaging.exchange.store=store.events
messaging.queue.email=email.order-events
messaging.routingKeys=order.*,delivery.*,refund.*

logging.level.root=INFO
logging.level.com.email.emailservice=DEBUG


